import type { ProductDetail, ProductSummary } from "@/lib/supabase/queries";

const fallbackDetails: ProductDetail[] = [
  {
    id: "fallback-travel-cot",
    name: "Travel cot",
    slug: "travel-cot",
    description:
      "Development preview: a compact travel cot for sleep during a Rabat stay. Exact model, fit, and availability are confirmed after request.",
    image_gallery: [],
    daily_price_mad: 60,
    weekly_price_mad: 300,
    monthly_price_mad: 900,
    deposit_mad: 500,
    included_items: ["Travel cot frame", "Mattress pad", "Carry bag"],
    optional_accessories: [],
    safety_notes: "Follow manufacturer age and weight limits. Condition and cleanliness are reviewed before handover.",
    cleaning_notes: "Cleaned, checked, and prepared before delivery.",
    age_guidance: "Newborn to about 3 years",
    weight_guidance: "Up to about 15 kg",
    height_guidance: null,
    requires_child_details: false,
    availability_mode: "request",
    model_image_note: true,
    display_order: 1,
    inventory_availability: {
      total_inventory_count: 0,
      usable_inventory_count: 0,
      has_usable_inventory: false,
    },
  },
  {
    id: "fallback-compact-stroller",
    name: "Compact stroller",
    slug: "compact-stroller",
    description:
      "Development preview: a lightweight stroller for airport arrivals, city walks, and family visits.",
    image_gallery: [],
    daily_price_mad: 50,
    weekly_price_mad: 250,
    monthly_price_mad: 750,
    deposit_mad: 400,
    included_items: ["Stroller", "Rain cover"],
    optional_accessories: [],
    safety_notes: "Harness use is required. Exact stroller model is confirmed before delivery.",
    cleaning_notes: "Wiped down, checked, and prepared before each rental.",
    age_guidance: "About 6 months and up",
    weight_guidance: "Up to about 22 kg",
    height_guidance: null,
    requires_child_details: false,
    availability_mode: "request",
    model_image_note: true,
    display_order: 2,
    inventory_availability: {
      total_inventory_count: 0,
      usable_inventory_count: 0,
      has_usable_inventory: false,
    },
  },
  {
    id: "fallback-infant-car-seat",
    name: "Infant car seat",
    slug: "infant-car-seat",
    description:
      "Development preview: rear-facing infant car seat request. Parents select the appropriate car seat group using the listed specifications.",
    image_gallery: [],
    daily_price_mad: 50,
    weekly_price_mad: 250,
    monthly_price_mad: 700,
    deposit_mad: 500,
    included_items: ["Infant car seat", "Base if available"],
    optional_accessories: [],
    safety_notes:
      "Parents are responsible for choosing the appropriate car seat group based on the listed age, weight, height, and manufacturer guidance.",
    cleaning_notes: "Cleaned and inspected before each rental.",
    age_guidance: "Newborn to about 12 months",
    weight_guidance: "About 0-13 kg",
    height_guidance: "Check the listed manufacturer guidance before requesting",
    requires_child_details: true,
    availability_mode: "confirm",
    model_image_note: true,
    display_order: 3,
    inventory_availability: {
      total_inventory_count: 0,
      usable_inventory_count: 0,
      has_usable_inventory: false,
    },
  },
];

export const fallbackProductDetails = fallbackDetails;

export const fallbackProductSummaries: ProductSummary[] = fallbackDetails.map(
  ({
    id,
    name,
    slug,
    description,
    daily_price_mad,
    weekly_price_mad,
    deposit_mad,
    availability_mode,
    inventory_availability,
    display_order,
  }) => ({
    id,
    name,
    slug,
    description,
    daily_price_mad,
    weekly_price_mad,
    deposit_mad,
    availability_mode,
    inventory_availability,
    display_order,
  })
);
